events {}

http {
    include /etc/nginx/mime.types;

    upstream api_cluster {
        server proyecto-api-1:8000;
        server proyecto-api-2:8000;
        server proyecto-api-3:8000;
    }

    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location ~ ^/(retos|evaluar|health) {
            proxy_pass http://api_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
